[package]
name = "incredible-operator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "eigen layer operator"
    
[lints]
workspace = true

[dependencies]
alloy.workspace = true
alloy-provider.workspace = true
incredible-config.workspace = true
thiserror.workspace = true
incredible-bindings.workspace = true
eyre.workspace = true
futures-util.workspace = true

# eigen-rs
eigen-client-avsregistry.workspace = true
eigen-crypto-bls.workspace = true
eigen-types.workspace = true
eigen-crypto-keystore.workspace = true

incredible-metrics.workspace = true

#bn254
rust-bls-bn254 = {git = "ssh://git@github.com/Layr-Labs/rust-bls-bn254.git", rev = "2ebe5f4", features = ["std"] }

#incredible
incredible-aggregator.workspace = true
reqwest.workspace = true


tokio.workspace = true
serde_json.workspace = true
tracing.workspace = true

