[package]
name = "incredible-aggregator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "eigen layer aggregator utils "

[lints]
workspace = true

[dependencies]
alloy.workspace = true
ark-ec.workspace = true
incredible-chainio.workspace = true
incredible-config.workspace = true
incredible-bindings.workspace = true
incredible-metrics.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

# eigensdk-rs
eigensdk.workspace = true
