[package]
name = "incredible-squaring"
version = "0.0.1-alpha"
edition = "2021"
rust-version = "1.81"
repository = "https://github.com/Layr-Labs/incredible-squaring-avs-rs"
homepage = ""
license = "Business Source License 1.1"

[dependencies]
alloy = { version = "0.13", features = [
    "sol-types",
    "contract",
    "full",
    "signer-aws",
    "signer-keystore",
    "rlp",
    "json-rpc",
] }
clap = { version = "4.5", features = ["derive"] }
eigensdk = { git = "https://github.com/Layr-Labs/eigensdk-rs", branch = "v2-dev-2", features = ["full"] }
thiserror = "1.0"
tokio = { version = "1.41", features = ["test-util", "full", "sync"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
serde = { version = "1.0", features = ["derive"] }

[lib]
doctest = false

[[bin]]
name = "incredible-squaring-aggregator"
path = "src/bin/aggregator.rs"

[[bin]]
name = "incredible-squaring-challenger"
path = "src/bin/challenger.rs"

[[bin]]
name = "incredible-squaring-operator"
path = "src/bin/operator.rs"

[[bin]]
name = "incredible-squaring-task-spammer"
path = "src/bin/task_spammer.rs"
