[workspace]
members = ["crates/aggregator",
"crates/operator",
"bin/incredible-squaring-avs",
"crates/cli",
"crates/config",
"crates/bindings"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
rust-version = "1.79"
repository = "https://github.com/Layr-Labs/incredible-squaring-avs-rust"
homepage = ""
license = "Business Source License 1.1"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
clap = "4"
eyre = "0.6.12"
tokio = { version = "1.21", default-features = false }
tracing = "0.1.0"
thiserror = "1.0.61"

#alloy
alloy = { version = "0.1", features = ["full","signer-keystore"] }



incredible-operator = {path = "crates/operator/"}
incredible-aggregator = {path = "crates/aggregator/"}
incredible-avs = {path = "bin/incredible/"}
incredible-cli-runner = {path = "crates/cli/"}
incredible-config = {path = "crates/config/"}
incredible-bindings = {path = "crates/bindings/"}