[workspace]
members = ["crates/aggregator",
"crates/operator",
"bin/incredible-squaring-avs",
"crates/cli",
"crates/config",
"crates/bindings",
"crates/avs",
"crates/challenger",
"crates/chainio"
]

resolver = "2"

[workspace.package]
version = "0.0.1-alpha"
edition = "2021"
rust-version = "1.79"
repository = "https://github.com/Layr-Labs/incredible-squaring-avs-rust"
homepage = ""
license = "Business Source License 1.1"


[workspace.lints]
rust.missing_debug_implementations = "warn"
rust.missing_docs = "warn"
rust.unreachable_pub = "warn"
rust.unused_must_use = "deny"
rust.rust_2018_idioms = "deny"
rustdoc.all = "warn"


[workspace.dependencies]
clap = "4"
eyre = "0.6.12"
tokio = { version = "1.21", default-features = false }
thiserror = "1.0.61"
ark-bn254 = { version = "0.4.0", features = ["curve"], default-features = false }
futures-util = "0.3"
metrics = "0.21.1"
reqwest = "0.12.5"
serde_json = "1.0.120"
#alloy
alloy = { version = "0.1", features = ["full","signer-keystore"] }
alloy-provider = { version = "0.1", default-features = false, features = [
    "reqwest",
] }
serde = "1.0.203"
tracing = "0.1.40"

incredible-operator = {path = "crates/operator/"}
incredible-aggregator = {path = "crates/aggregator/"}
incredible-squaring-avs = {path = "bin/incredible-squaring-avs/"}
incredible-cli-runner = {path = "crates/cli/"}
incredible-config = {path = "crates/config/"}
incredible-bindings = {path = "crates/bindings/"}
incredible-metrics  = {path = "crates/metrics/"}
incredible-avs = {path = "crates/avs/"}
incredible-challenger = {path = "crates/challenger/"}
incredible-chainio = {path = "crates/chainio/"}

# eigen-rs 
eigen-client-avsregistry  = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-testing-utils =  {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-crypto-bls =  {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-types =  {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-crypto-keystore = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-metrics = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-metrics-derive = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-utils = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
eigen-contract-bindings = {git = "https://github.com/supernovahs/eigen-rs" , rev = "29e17a6"}
