[package]
name = "incredible-challenger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "incredible squaring challenger "
    
[lints]
workspace = true

[dependencies]
alloy.workspace = true
eigensdk.workspace = true
