[package]
name = "incredible-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = " incredible squaring configuration "
    
[lints]
workspace = true

[dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing.workspace = true
alloy.workspace = true


#eigen
eigen-types.workspace = true