[package]
name = "incredible-squaring-avs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "incredible squaring avs in rust"

[lints]
workspace = true

[dependencies]
incredible-aggregator.workspace = true
incredible-operator = { workspace = true, features = ["default"] }
incredible-cli-runner.workspace = true
incredible-config.workspace = true
incredible-avs.workspace = true
incredible-metrics.workspace = true
incredible-testing-utils.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true
alloy.workspace = true
tracing.workspace = true
hex = "0.4.3"
metrics-exporter-prometheus = "0.15.3"
rust-bls-bn254.workspace = true
metrics-util = "0.17.0"

# eigensdk-rs
eigensdk.workspace = true

[dev-dependencies]
tokio.workspace = true


[[bin]]
name = "incredible-squaring-avs"
path = "src/main.rs"
