[package]
name = "incredible-squaring-avs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "incredible squaring avs in rust"
    
[lints]
workspace = true

[dependencies]
incredible-aggregator.workspace = true
incredible-operator.workspace = true
incredible-cli-runner.workspace = true
incredible-config.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
eyre.workspace = true


[[bin]]
name = "incredible-squaring-avs"
path = "src/main.rs"