[package]
name = "incredible-slasher"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "incredible squaring slasher"
    
[lints]
workspace = true