[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "integration tests for incredible avs"
    
[lints]
workspace = true

[dev-dependencies]
alloy.workspace = true
tokio.workspace = true

