[package]
name = "integration-tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true
description = "integration tests for incredible avs"
    
[lints]
workspace = true


[dependencies]
alloy.workspace = true
eigen-utils.workspace = true
eigen-logging.workspace = true
incredible-config.workspace = true
incredible-challenger.workspace = true
incredible-testing-utils.workspace = true
incredible-bindings.workspace = true
incredible-task-generator.workspace = true
incredible-operator.workspace = true
incredible-aggregator.workspace = true
toml.workspace = true

[dev-dependencies]
tokio.workspace = true
