name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.80.1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo check
        run: cargo check --workspace --all-features --all-targets --exclude incredible-bindings

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.80.1
        with:
            components: rustfmt, clippy

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --workspace --all-features --benches --examples --tests -- -D warnings 

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install nightly Rust
        run: rustup toolchain install nightly

      - name: Install testing tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Install Foundry
        run: cargo install --git https://github.com/foundry-rs/foundry --profile release --locked cast anvil

      - name: docker
        uses: docker-practice/actions-setup-docker@master

      - name: Run unit tests
        run: make pr

      - name: Run Integration tests
        run: make integration-tests
